apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-dev-grafana-config
  namespace: petclinic-dev
data:
  grafana.ini: |
    app_mode = development
    [paths]
    provisioning = /etc/grafana/provisioning
    [server]
    enable_gzip = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://petclinic-dev-prometheus:9090
        isDefault: true
        editable: true
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/dashboards
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-dev-grafana
  namespace: petclinic-dev
  labels:
    app: petclinic-dev-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-dev-grafana
  template:
    metadata:
      labels:
        app: petclinic-dev-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
      volumes:
        - name: grafana-config
          configMap:
            name: petclinic-dev-grafana-config
            items:
              - key: grafana.ini
                path: grafana.ini
        - name: grafana-datasources
          configMap:
            name: petclinic-dev-grafana-config
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-dashboards-config
          configMap:
            name: petclinic-dev-grafana-config
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-dev-grafana
  namespace: petclinic-dev
spec:
  selector:
    app: petclinic-dev-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
